# Generated by Django 6.0.4 on 2026-04-16 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_rename_lotacao_id_servidor_lotacao'),
        ('setores', '0002_alter_setor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='chefe_imediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servidores.servidor', verbose_name='Chefe Imediato'),
        ),
        migrations.AddField(
            model_name='setor',
            name='matricula_chefe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
    ]
