# Generated by Django 6.0.4 on 2026-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0003_setor_chefe_imediato_setor_matricula_chefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='cargo_chefe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Chefe'),
        ),
        migrations.AddField(
            model_name='setor',
            name='portaria_chefe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Portaria'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='chefe_imediato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chefe Imediato'),
        ),
    ]
