# Generated by Django 6.0.4 on 2026-04-19 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0009_remove_servidor_lotacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoristaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('vinculo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20)),
                ('lotacao', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta_corrente', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ida', models.DateField()),
                ('data_retorno', models.DateField()),
                ('municipio', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('processado', models.BooleanField(default=False)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_visualizar', models.BooleanField(default=False)),
                ('pode_processar', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessamentoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('servidor', 'Servidor'), ('outros', 'Outros')], max_length=20)),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento')),
                ('motorista_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.motoristaexterno')),
                ('motorista_servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor')),
            ],
        ),
    ]
