# Generated by Django 6.0.4 on 2026-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoristaexterno',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
