# Generated by Django 6.0.4 on 2026-04-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_motoristaexterno_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentoagendamento',
            name='numero_processo',
        ),
    ]
