# Generated by Django 6.0.4 on 2026-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_remove_processamentoagendamento_numero_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoristaexterno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
