# Generated by Django 6.0.4 on 2026-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_motoristaexterno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentoagendamento',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processamentoagendamento',
            name='tipo',
            field=models.CharField(choices=[('Da Vigilância', 'Da Vigilância'), ('outros', 'Outros')], max_length=20),
        ),
    ]
