# Generated by Django 6.0.4 on 2026-04-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_processamentoagendamento_numero_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentoagendamento',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processamento', to='agendamentos.agendamento'),
        ),
    ]
