# Generated by Django 6.0.4 on 2026-05-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_alter_processamentoagendamento_agendamento'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoristaexterno',
            name='lotacao',
        ),
        migrations.AddField(
            model_name='motoristaexterno',
            name='chefe_imediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_externos_chefiados', to='setores.setor'),
        ),
        migrations.AddField(
            model_name='motoristaexterno',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
