# Generated by Django 6.0.4 on 2026-05-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_remove_motoristaexterno_lotacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoristaexterno',
            old_name='conta_corrente',
            new_name='conta',
        ),
        migrations.RenameField(
            model_name='motoristaexterno',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
