# Generated by Django 6.0.4 on 2026-05-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_rename_conta_corrente_motoristaexterno_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentoagendamento',
            name='numero_processo',
        ),
    ]
