# Generated by Django 6.0.4 on 2026-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_remove_processamentoagendamento_numero_processo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='processado',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
