# Generated by Django 6.0.4 on 2026-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_remove_agendamento_processado_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='transporte',
            field=models.CharField(choices=[('Aéreo', 'Aéreo'), ('Veículo Oficial', 'Veículo Oficial'), ('Fluvial', 'Fluvial'), ('Outro', 'Outro')], default='Veículo Oficial', max_length=50),
        ),
    ]
