# Generated by Django 6.0.4 on 2026-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_agendamento_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='transporte',
            field=models.CharField(choices=[('Aéreo', 'Aéreo'), ('Veículo Oficial', 'Veículo Oficial'), ('Veículo Oficial (VAN)', 'Veículo Oficial (VAN)'), ('Fluvial', 'Fluvial'), ('Outro', 'Outro')], default='Veículo Oficial', max_length=50),
        ),
    ]
