# Generated by Django 6.0.4 on 2026-05-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_alter_agendamento_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='memorando_matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='memorando_nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='memorando_setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='n_memorando',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
