# Generated by Django 6.0.4 on 2026-05-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_agendamento_memorando_matricula_and_more'),
        ('servidores', '0015_historicosituacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='memorando_servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_memorando', to='servidores.servidor'),
        ),
    ]
