# Generated by Django 6.0.4 on 2026-04-09 02:08

import django.db.models.deletion
import usuarios.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.managers.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setores.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('funcionario', 'Funcionário')], max_length=20, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
