# Generated by Django 6.0.4 on 2026-04-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_remove_servidor_ferias_licencas_and_more'),
        ('usuarios', '0002_alter_usuario_managers_alter_usuario_setor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='servidor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='servidores.servidor'),
        ),
    ]
