# Generated by Django 6.0.4 on 2026-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
