# Generated by Django 6.0.4 on 2026-04-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
    ]
