# Generated by Django 6.0.4 on 2026-04-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
        ('usuarios', '0007_remove_usuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='setores.setor'),
        ),
    ]
