# Generated by Django 6.0.4 on 2026-04-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
    ]
