# Generated by Django 6.0.4 on 2026-04-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_nome', models.CharField(max_length=200)),
                ('servidor_matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('servidor_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_atividade', models.CharField(choices=[('Viagem', 'Viagem')], max_length=50)),
                ('periodo_viagem', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_diarias', models.CharField(blank=True, max_length=50, null=True)),
                ('pernoite', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('transporte', models.CharField(blank=True, max_length=50, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('data_ida', models.DateField(blank=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
