# Generated by Django 6.0.4 on 2026-04-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='periodo_viagem',
        ),
    ]
