# Generated by Django 6.0.4 on 2026-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_remove_atividade_periodo_viagem'),
        ('servidores', '0003_remove_servidor_data_remove_servidor_dias_diarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='servidores',
            field=models.ManyToManyField(related_name='atividades', to='servidores.servidor'),
        ),
    ]
