# Generated by Django 6.0.4 on 2026-04-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividade_servidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='servidor_cargo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='servidor_matricula',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='servidor_nome',
        ),
    ]
