# Generated by Django 6.0.4 on 2026-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_remove_atividade_servidor_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
