# Generated by Django 6.0.4 on 2026-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_atividade_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(blank=True, choices=[('Viagem', 'Viagem')], max_length=50, null=True),
        ),
    ]
