# Generated by Django 6.0.4 on 2026-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0006_alter_atividade_tipo_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='n_memorando',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Nº do Memorando'),
        ),
    ]
