# Generated by Django 6.0.4 on 2026-04-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0007_atividade_n_memorando'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='chefe_imediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_chefiadas', to='setores.setor'),
        ),
    ]
