# Generated by Django 6.0.4 on 2026-04-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_atividade_chefe_imediato'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='recurso',
            field=models.CharField(blank=True, default='01', max_length=2, null=True),
        ),
    ]
