# Generated by Django 6.0.4 on 2026-04-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_atividade_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='recurso',
            field=models.CharField(blank=True, choices=[('01', 'Exercício'), ('02', 'Superávit')], default='01', max_length=2, null=True),
        ),
    ]
