# Generated by Django 6.0.4 on 2026-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_alter_atividade_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
