# Generated by Django 6.0.4 on 2026-04-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0011_atividade_numero_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('01', 'Exercício'), ('02', 'Superávit')], max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.recursoativo'),
        ),
    ]
