# Generated by Django 6.0.4 on 2026-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0012_recursoativo_alter_atividade_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='recurso',
        ),
        migrations.AddField(
            model_name='atividade',
            name='recurso_codigo',
            field=models.CharField(choices=[('01', 'Exercício'), ('02', 'Superávit')], default='01', max_length=2),
        ),
    ]
