# Generated by Django 6.0.4 on 2026-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_remove_motoristaexterno_lotacao_and_more'),
        ('atividades', '0014_atividade_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='motoristas_externos',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='agendamentos.motoristaexterno'),
        ),
    ]
