# Generated by Django 6.0.4 on 2026-05-09 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_rename_conta_corrente_motoristaexterno_conta_and_more'),
        ('atividades', '0015_atividade_motoristas_externos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividade', to='agendamentos.agendamento'),
        ),
    ]
