# Generated by Django 6.0.4 on 2026-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0016_atividade_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('FACULTADO', 'Facultado')], max_length=10)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
