# Generated by Django 6.0.4 on 2026-05-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0020_alter_atividade_n_memorando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='n_memorando',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Nº do Memorando'),
        ),
    ]
