# Generated by Django 6.0.4 on 2026-05-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0023_atividade_unique_memorando_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atividade',
            name='unique_memorando_not_null',
        ),
    ]
