# Generated by Django 6.0.4 on 2026-05-27 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_alter_agendamento_transporte'),
        ('atividades', '0024_remove_atividade_unique_memorando_not_null'),
        ('servidores', '0015_historicosituacao'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(condition=models.Q(('n_memorando', None), _negated=True), fields=('n_memorando',), name='unique_memorando_not_null'),
        ),
    ]
