# Generated by Django 6.0.4 on 2026-05-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0025_atividade_unique_memorando_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atividade',
            name='unique_memorando_not_null',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='n_memorando',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Nº do Memorando'),
        ),
    ]
