# Generated by Django 6.0.4 on 2026-05-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0026_remove_atividade_unique_memorando_not_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='pernoite',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, null=True),
        ),
    ]
