# Generated by Django 6.0.4 on 2026-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0028_alter_atividade_n_memorando'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARA', 'Dentro do Pará'), ('OUTROS', 'Outros Estados')], max_length=20, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
