# Generated by Django 6.0.4 on 2026-06-25 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0029_valordiaria'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portaria_numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('objetivo', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('horario_partida', models.TimeField()),
                ('horario_guarda', models.TimeField()),
                ('devolucao', models.CharField(choices=[('total', 'Devolução Total'), ('parcial', 'Devolução Parcial'), ('nao', 'Não se Aplica')], max_length=20)),
                ('anexos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='atividades.atividade')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
        ),
    ]
