# Generated by Django 6.0.4 on 2026-06-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0030_prestacaocontas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaocontas',
            name='atividade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='atividades.atividade'),
        ),
    ]
