# Generated by Django 6.0.4 on 2026-06-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0032_alter_prestacaocontas_atividade'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='anexos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_prestacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='devolucao',
            field=models.CharField(blank=True, choices=[('total', 'Devolução Total'), ('parcial', 'Devolução Parcial'), ('nao', 'Não se Aplica')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario_guarda',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario_partida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='objetivo_prestacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='observacao_prestacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='portaria_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='veiculo_prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo'),
        ),
        migrations.DeleteModel(
            name='PrestacaoContas',
        ),
    ]
