# Generated by Django 6.0.4 on 2026-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0033_atividade_anexos_atividade_data_prestacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
