# Generated by Django 6.0.4 on 2026-05-06 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('ano', models.IntegerField(default=2026)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
