# Generated by Django 6.0.4 on 2026-05-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandos', '0001_initial'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
