# Generated by Django 6.0.4 on 2026-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandos', '0002_alter_memorando_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='memorando',
            unique_together={('numero', 'ano')},
        ),
    ]
