# Generated by Django 6.0.4 on 2026-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('vinculo', models.CharField(choices=[('Servidor do Órgão', 'Servidor do Órgão'), ('Servidor Cedido', 'Servidor Cedido'), ('Colaborador Eventual', 'Colaborador Eventual')], max_length=50)),
                ('matricula', models.PositiveIntegerField(unique=True)),
                ('lotacao', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True)),
                ('periodo_viagem', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_diarias', models.CharField(blank=True, max_length=50, null=True)),
                ('pernoite', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('transporte', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('ferias_licencas', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('chefia', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
