# Generated by Django 6.0.4 on 2026-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='ferias_licencas',
        ),
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
