# Generated by Django 6.0.4 on 2026-04-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_remove_servidor_ferias_licencas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='dias_diarias',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='periodo_viagem',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='pernoite',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='transporte',
        ),
    ]
