# Generated by Django 6.0.4 on 2026-04-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_remove_servidor_data_remove_servidor_dias_diarias_and_more'),
        ('setores', '0002_alter_setor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setores.setor'),
        ),
    ]
