# Generated by Django 6.0.4 on 2026-04-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0004_alter_servidor_lotacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='lotacao',
            new_name='lotacao_id',
        ),
    ]
