# Generated by Django 6.0.4 on 2026-04-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0005_rename_lotacao_servidor_lotacao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='lotacao_id',
            new_name='lotacao',
        ),
    ]
