# Generated by Django 6.0.4 on 2026-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_rename_lotacao_id_servidor_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='lotacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lotação'),
        ),
    ]
