# Generated by Django 6.0.4 on 2026-04-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0007_alter_servidor_lotacao'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='chefia',
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
