# Generated by Django 6.0.4 on 2026-04-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0008_remove_servidor_chefia_servidor_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='lotacao',
        ),
    ]
