# Generated by Django 6.0.4 on 2026-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0009_remove_servidor_lotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
