# Generated by Django 6.0.4 on 2026-04-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0010_servidor_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='ultima_vez_sorteado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
