# Generated by Django 6.0.4 on 2026-05-02 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0011_servidor_ultima_vez_sorteado'),
        ('setores', '0004_setor_cargo_chefe_setor_portaria_chefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='chefe_imediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores_chefiados', to='setores.setor'),
        ),
    ]
