# Generated by Django 6.0.4 on 2026-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0012_servidor_chefe_imediato'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='horario_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='orgao_origem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
