# Generated by Django 6.0.4 on 2026-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0013_servidor_admissao_servidor_horario_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nome']},
        ),
    ]
