# Generated by Django 6.0.4 on 2026-05-25 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0014_alter_servidor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_situacoes', to='servidores.servidor')),
            ],
        ),
    ]
