# Generated by Django 6.0.4 on 2026-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0015_historicosituacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
